package mrthomas20121.rechiseled_compat.compat;

import com.mojang.datafixers.util.Pair;
import mrthomas20121.rechiseled_compat.core.Core;

import java.util.Collection;
import java.util.List;

public class Betternether extends Mod {
    public static final String[] PLANKS = {
            "betternether_anchor_tree_planks_beams",
            "betternether_anchor_tree_planks_beams_connecting",
            "betternether_anchor_tree_planks_bricks",
            "betternether_anchor_tree_planks_bricks_connecting",
            "betternether_anchor_tree_planks_crate",
            "betternether_anchor_tree_planks_crate_connecting",
            "betternether_anchor_tree_planks_diagonal_stripes",
            "betternether_anchor_tree_planks_diagonal_stripes_connecting",
            "betternether_anchor_tree_planks_diagonal_tiles",
            "betternether_anchor_tree_planks_diagonal_tiles_connecting",
            "betternether_anchor_tree_planks_dotted",
            "betternether_anchor_tree_planks_dotted_connecting",
            "betternether_anchor_tree_planks_flooring",
            "betternether_anchor_tree_planks_flooring_connecting",
            "betternether_anchor_tree_planks_large_tiles",
            "betternether_anchor_tree_planks_large_tiles_connecting",
            "betternether_anchor_tree_planks_pattern",
            "betternether_anchor_tree_planks_pattern_connecting",
            "betternether_anchor_tree_planks_small_bricks",
            "betternether_anchor_tree_planks_small_bricks_connecting",
            "betternether_anchor_tree_planks_small_tiles",
            "betternether_anchor_tree_planks_small_tiles_connecting",
            "betternether_anchor_tree_planks_squares",
            "betternether_anchor_tree_planks_squares_connecting",
            "betternether_anchor_tree_planks_tiles",
            "betternether_anchor_tree_planks_tiles_connecting",
            "betternether_anchor_tree_planks_wavy",
            "betternether_anchor_tree_planks_wavy_connecting",
            "betternether_anchor_tree_planks_woven",
            "betternether_anchor_tree_planks_woven_connecting",
            "betternether_mushroom_fir_planks_beams",
            "betternether_mushroom_fir_planks_beams_connecting",
            "betternether_mushroom_fir_planks_bricks",
            "betternether_mushroom_fir_planks_bricks_connecting",
            "betternether_mushroom_fir_planks_crate",
            "betternether_mushroom_fir_planks_crate_connecting",
            "betternether_mushroom_fir_planks_diagonal_stripes",
            "betternether_mushroom_fir_planks_diagonal_stripes_connecting",
            "betternether_mushroom_fir_planks_diagonal_tiles",
            "betternether_mushroom_fir_planks_diagonal_tiles_connecting",
            "betternether_mushroom_fir_planks_dotted",
            "betternether_mushroom_fir_planks_dotted_connecting",
            "betternether_mushroom_fir_planks_flooring",
            "betternether_mushroom_fir_planks_flooring_connecting",
            "betternether_mushroom_fir_planks_large_tiles",
            "betternether_mushroom_fir_planks_large_tiles_connecting",
            "betternether_mushroom_fir_planks_pattern",
            "betternether_mushroom_fir_planks_pattern_connecting",
            "betternether_mushroom_fir_planks_small_bricks",
            "betternether_mushroom_fir_planks_small_bricks_connecting",
            "betternether_mushroom_fir_planks_small_tiles",
            "betternether_mushroom_fir_planks_small_tiles_connecting",
            "betternether_mushroom_fir_planks_squares",
            "betternether_mushroom_fir_planks_squares_connecting",
            "betternether_mushroom_fir_planks_tiles",
            "betternether_mushroom_fir_planks_tiles_connecting",
            "betternether_mushroom_fir_planks_wavy",
            "betternether_mushroom_fir_planks_wavy_connecting",
            "betternether_mushroom_fir_planks_woven",
            "betternether_mushroom_fir_planks_woven_connecting",
            "betternether_mushroom_planks_beams",
            "betternether_mushroom_planks_beams_connecting",
            "betternether_mushroom_planks_bricks",
            "betternether_mushroom_planks_bricks_connecting",
            "betternether_mushroom_planks_crate",
            "betternether_mushroom_planks_crate_connecting",
            "betternether_mushroom_planks_diagonal_stripes",
            "betternether_mushroom_planks_diagonal_stripes_connecting",
            "betternether_mushroom_planks_diagonal_tiles",
            "betternether_mushroom_planks_diagonal_tiles_connecting",
            "betternether_mushroom_planks_dotted",
            "betternether_mushroom_planks_dotted_connecting",
            "betternether_mushroom_planks_flooring",
            "betternether_mushroom_planks_flooring_connecting",
            "betternether_mushroom_planks_large_tiles",
            "betternether_mushroom_planks_large_tiles_connecting",
            "betternether_mushroom_planks_pattern",
            "betternether_mushroom_planks_pattern_connecting",
            "betternether_mushroom_planks_small_bricks",
            "betternether_mushroom_planks_small_bricks_connecting",
            "betternether_mushroom_planks_small_tiles",
            "betternether_mushroom_planks_small_tiles_connecting",
            "betternether_mushroom_planks_squares",
            "betternether_mushroom_planks_squares_connecting",
            "betternether_mushroom_planks_tiles",
            "betternether_mushroom_planks_tiles_connecting",
            "betternether_mushroom_planks_wavy",
            "betternether_mushroom_planks_wavy_connecting",
            "betternether_mushroom_planks_woven",
            "betternether_mushroom_planks_woven_connecting",
            "betternether_nether_sakura_planks_beams",
            "betternether_nether_sakura_planks_beams_connecting",
            "betternether_nether_sakura_planks_bricks",
            "betternether_nether_sakura_planks_bricks_connecting",
            "betternether_nether_sakura_planks_crate",
            "betternether_nether_sakura_planks_crate_connecting",
            "betternether_nether_sakura_planks_diagonal_stripes",
            "betternether_nether_sakura_planks_diagonal_stripes_connecting",
            "betternether_nether_sakura_planks_diagonal_tiles",
            "betternether_nether_sakura_planks_diagonal_tiles_connecting",
            "betternether_nether_sakura_planks_dotted",
            "betternether_nether_sakura_planks_dotted_connecting",
            "betternether_nether_sakura_planks_flooring",
            "betternether_nether_sakura_planks_flooring_connecting",
            "betternether_nether_sakura_planks_large_tiles",
            "betternether_nether_sakura_planks_large_tiles_connecting",
            "betternether_nether_sakura_planks_pattern",
            "betternether_nether_sakura_planks_pattern_connecting",
            "betternether_nether_sakura_planks_small_bricks",
            "betternether_nether_sakura_planks_small_bricks_connecting",
            "betternether_nether_sakura_planks_small_tiles",
            "betternether_nether_sakura_planks_small_tiles_connecting",
            "betternether_nether_sakura_planks_squares",
            "betternether_nether_sakura_planks_squares_connecting",
            "betternether_nether_sakura_planks_tiles",
            "betternether_nether_sakura_planks_tiles_connecting",
            "betternether_nether_sakura_planks_wavy",
            "betternether_nether_sakura_planks_wavy_connecting",
            "betternether_nether_sakura_planks_woven",
            "betternether_nether_sakura_planks_woven_connecting",
            "betternether_rubeus_planks_beams",
            "betternether_rubeus_planks_beams_connecting",
            "betternether_rubeus_planks_bricks",
            "betternether_rubeus_planks_bricks_connecting",
            "betternether_rubeus_planks_crate",
            "betternether_rubeus_planks_crate_connecting",
            "betternether_rubeus_planks_diagonal_stripes",
            "betternether_rubeus_planks_diagonal_stripes_connecting",
            "betternether_rubeus_planks_diagonal_tiles",
            "betternether_rubeus_planks_diagonal_tiles_connecting",
            "betternether_rubeus_planks_dotted",
            "betternether_rubeus_planks_dotted_connecting",
            "betternether_rubeus_planks_flooring",
            "betternether_rubeus_planks_flooring_connecting",
            "betternether_rubeus_planks_large_tiles",
            "betternether_rubeus_planks_large_tiles_connecting",
            "betternether_rubeus_planks_pattern",
            "betternether_rubeus_planks_pattern_connecting",
            "betternether_rubeus_planks_small_bricks",
            "betternether_rubeus_planks_small_bricks_connecting",
            "betternether_rubeus_planks_small_tiles",
            "betternether_rubeus_planks_small_tiles_connecting",
            "betternether_rubeus_planks_squares",
            "betternether_rubeus_planks_squares_connecting",
            "betternether_rubeus_planks_tiles",
            "betternether_rubeus_planks_tiles_connecting",
            "betternether_rubeus_planks_wavy",
            "betternether_rubeus_planks_wavy_connecting",
            "betternether_rubeus_planks_woven",
            "betternether_rubeus_planks_woven_connecting",
            "betternether_stalagnate_planks_beams",
            "betternether_stalagnate_planks_beams_connecting",
            "betternether_stalagnate_planks_bricks",
            "betternether_stalagnate_planks_bricks_connecting",
            "betternether_stalagnate_planks_crate",
            "betternether_stalagnate_planks_crate_connecting",
            "betternether_stalagnate_planks_diagonal_stripes",
            "betternether_stalagnate_planks_diagonal_stripes_connecting",
            "betternether_stalagnate_planks_diagonal_tiles",
            "betternether_stalagnate_planks_diagonal_tiles_connecting",
            "betternether_stalagnate_planks_dotted",
            "betternether_stalagnate_planks_dotted_connecting",
            "betternether_stalagnate_planks_flooring",
            "betternether_stalagnate_planks_flooring_connecting",
            "betternether_stalagnate_planks_large_tiles",
            "betternether_stalagnate_planks_large_tiles_connecting",
            "betternether_stalagnate_planks_pattern",
            "betternether_stalagnate_planks_pattern_connecting",
            "betternether_stalagnate_planks_small_bricks",
            "betternether_stalagnate_planks_small_bricks_connecting",
            "betternether_stalagnate_planks_small_tiles",
            "betternether_stalagnate_planks_small_tiles_connecting",
            "betternether_stalagnate_planks_squares",
            "betternether_stalagnate_planks_squares_connecting",
            "betternether_stalagnate_planks_tiles",
            "betternether_stalagnate_planks_tiles_connecting",
            "betternether_stalagnate_planks_wavy",
            "betternether_stalagnate_planks_wavy_connecting",
            "betternether_stalagnate_planks_woven",
            "betternether_stalagnate_planks_woven_connecting",
            "betternether_wart_planks_beams",
            "betternether_wart_planks_beams_connecting",
            "betternether_wart_planks_bricks",
            "betternether_wart_planks_bricks_connecting",
            "betternether_wart_planks_crate",
            "betternether_wart_planks_crate_connecting",
            "betternether_wart_planks_diagonal_stripes",
            "betternether_wart_planks_diagonal_stripes_connecting",
            "betternether_wart_planks_diagonal_tiles",
            "betternether_wart_planks_diagonal_tiles_connecting",
            "betternether_wart_planks_dotted",
            "betternether_wart_planks_dotted_connecting",
            "betternether_wart_planks_flooring",
            "betternether_wart_planks_flooring_connecting",
            "betternether_wart_planks_large_tiles",
            "betternether_wart_planks_large_tiles_connecting",
            "betternether_wart_planks_pattern",
            "betternether_wart_planks_pattern_connecting",
            "betternether_wart_planks_small_bricks",
            "betternether_wart_planks_small_bricks_connecting",
            "betternether_wart_planks_small_tiles",
            "betternether_wart_planks_small_tiles_connecting",
            "betternether_wart_planks_squares",
            "betternether_wart_planks_squares_connecting",
            "betternether_wart_planks_tiles",
            "betternether_wart_planks_tiles_connecting",
            "betternether_wart_planks_wavy",
            "betternether_wart_planks_wavy_connecting",
            "betternether_wart_planks_woven",
            "betternether_wart_planks_woven_connecting",
            "betternether_willow_planks_beams",
            "betternether_willow_planks_beams_connecting",
            "betternether_willow_planks_bricks",
            "betternether_willow_planks_bricks_connecting",
            "betternether_willow_planks_crate",
            "betternether_willow_planks_crate_connecting",
            "betternether_willow_planks_diagonal_stripes",
            "betternether_willow_planks_diagonal_stripes_connecting",
            "betternether_willow_planks_diagonal_tiles",
            "betternether_willow_planks_diagonal_tiles_connecting",
            "betternether_willow_planks_dotted",
            "betternether_willow_planks_dotted_connecting",
            "betternether_willow_planks_flooring",
            "betternether_willow_planks_flooring_connecting",
            "betternether_willow_planks_large_tiles",
            "betternether_willow_planks_large_tiles_connecting",
            "betternether_willow_planks_pattern",
            "betternether_willow_planks_pattern_connecting",
            "betternether_willow_planks_small_bricks",
            "betternether_willow_planks_small_bricks_connecting",
            "betternether_willow_planks_small_tiles",
            "betternether_willow_planks_small_tiles_connecting",
            "betternether_willow_planks_squares",
            "betternether_willow_planks_squares_connecting",
            "betternether_willow_planks_tiles",
            "betternether_willow_planks_tiles_connecting",
            "betternether_willow_planks_wavy",
            "betternether_willow_planks_wavy_connecting",
            "betternether_willow_planks_woven",
            "betternether_willow_planks_woven_connecting"
    };

    private Betternether() {
    }

    public String getModId() {
        return "betternether";
    }

    public void registerBlocks() {

        for (String block : PLANKS) {
            Core.registerBlock("minecraft:oak_planks", block);
        }

    }

    // for data generation
    @Override
    public Collection<Pair<String[], String[]>> getBlockTags() {
        return List.of(
                Pair.of(PLANKS, new String[]{
                    "minecraft:planks",
                    "minecraft:mineable/axe"
                })/*,
                Pair.of(STONES, new String[]{
                    ...
                })*/
        );
    }

    // for data generation
    @Override
    public Collection<Pair<String[], String[]>> getItemTags() {
        return List.of(
                Pair.of(PLANKS, new String[]{
                        "minecraft:planks",
                })
        );
    }
}