package mrthomas20121.rechiseled_compat.compat;

import mrthomas20121.rechiseled_compat.RechiseledCompat;
import mrthomas20121.rechiseled_compat.block.ChiseledBlock;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
public class TconstructBlocks {

    public static DeferredRegister<Block> BLOCKS = DeferredRegister.create(Block.class, RechiseledCompat.MOD_ID);

    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_BEAMS = BLOCKS.register("tconstruct_greenheart_planks_beams", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_BEAMS_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_beams_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_BRICKS = BLOCKS.register("tconstruct_greenheart_planks_bricks", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_BRICKS_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_bricks_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_CRATE = BLOCKS.register("tconstruct_greenheart_planks_crate", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_CRATE_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_crate_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_DIAGONAL_STRIPES = BLOCKS.register("tconstruct_greenheart_planks_diagonal_stripes", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_DIAGONAL_STRIPES_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_diagonal_stripes_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_DIAGONAL_TILES = BLOCKS.register("tconstruct_greenheart_planks_diagonal_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_DIAGONAL_TILES_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_diagonal_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_DOTTED = BLOCKS.register("tconstruct_greenheart_planks_dotted", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_DOTTED_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_dotted_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_FLOORING = BLOCKS.register("tconstruct_greenheart_planks_flooring", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_FLOORING_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_flooring_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_LARGE_TILES = BLOCKS.register("tconstruct_greenheart_planks_large_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_LARGE_TILES_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_large_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_PATTERN = BLOCKS.register("tconstruct_greenheart_planks_pattern", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_PATTERN_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_pattern_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_SMALL_BRICKS = BLOCKS.register("tconstruct_greenheart_planks_small_bricks", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_SMALL_BRICKS_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_small_bricks_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_SMALL_TILES = BLOCKS.register("tconstruct_greenheart_planks_small_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_SMALL_TILES_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_small_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_SQUARES = BLOCKS.register("tconstruct_greenheart_planks_squares", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_SQUARES_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_squares_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_TILES = BLOCKS.register("tconstruct_greenheart_planks_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_TILES_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_WAVY = BLOCKS.register("tconstruct_greenheart_planks_wavy", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_WAVY_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_wavy_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_WOVEN = BLOCKS.register("tconstruct_greenheart_planks_woven", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_GREENHEART_PLANKS_WOVEN_CONNECTING = BLOCKS.register("tconstruct_greenheart_planks_woven_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_BEAMS = BLOCKS.register("tconstruct_skyroot_planks_beams", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_BEAMS_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_beams_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_BRICKS = BLOCKS.register("tconstruct_skyroot_planks_bricks", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_BRICKS_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_bricks_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_CRATE = BLOCKS.register("tconstruct_skyroot_planks_crate", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_CRATE_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_crate_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_DIAGONAL_STRIPES = BLOCKS.register("tconstruct_skyroot_planks_diagonal_stripes", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_DIAGONAL_STRIPES_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_diagonal_stripes_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_DIAGONAL_TILES = BLOCKS.register("tconstruct_skyroot_planks_diagonal_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_DIAGONAL_TILES_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_diagonal_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_DOTTED = BLOCKS.register("tconstruct_skyroot_planks_dotted", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_DOTTED_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_dotted_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_FLOORING = BLOCKS.register("tconstruct_skyroot_planks_flooring", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_FLOORING_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_flooring_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_LARGE_TILES = BLOCKS.register("tconstruct_skyroot_planks_large_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_LARGE_TILES_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_large_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_PATTERN = BLOCKS.register("tconstruct_skyroot_planks_pattern", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_PATTERN_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_pattern_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_SMALL_BRICKS = BLOCKS.register("tconstruct_skyroot_planks_small_bricks", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_SMALL_BRICKS_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_small_bricks_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_SMALL_TILES = BLOCKS.register("tconstruct_skyroot_planks_small_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_SMALL_TILES_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_small_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_SQUARES = BLOCKS.register("tconstruct_skyroot_planks_squares", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_SQUARES_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_squares_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_TILES = BLOCKS.register("tconstruct_skyroot_planks_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_TILES_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_WAVY = BLOCKS.register("tconstruct_skyroot_planks_wavy", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_WAVY_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_wavy_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_WOVEN = BLOCKS.register("tconstruct_skyroot_planks_woven", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_SKYROOT_PLANKS_WOVEN_CONNECTING = BLOCKS.register("tconstruct_skyroot_planks_woven_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_BEAMS = BLOCKS.register("tconstruct_bloodshroom_planks_beams", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_BEAMS_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_beams_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_BRICKS = BLOCKS.register("tconstruct_bloodshroom_planks_bricks", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_BRICKS_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_bricks_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_CRATE = BLOCKS.register("tconstruct_bloodshroom_planks_crate", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_CRATE_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_crate_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_DIAGONAL_STRIPES = BLOCKS.register("tconstruct_bloodshroom_planks_diagonal_stripes", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_DIAGONAL_STRIPES_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_diagonal_stripes_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_DIAGONAL_TILES = BLOCKS.register("tconstruct_bloodshroom_planks_diagonal_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_DIAGONAL_TILES_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_diagonal_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_DOTTED = BLOCKS.register("tconstruct_bloodshroom_planks_dotted", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_DOTTED_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_dotted_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_FLOORING = BLOCKS.register("tconstruct_bloodshroom_planks_flooring", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_FLOORING_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_flooring_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_LARGE_TILES = BLOCKS.register("tconstruct_bloodshroom_planks_large_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_LARGE_TILES_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_large_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_PATTERN = BLOCKS.register("tconstruct_bloodshroom_planks_pattern", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_PATTERN_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_pattern_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_SMALL_BRICKS = BLOCKS.register("tconstruct_bloodshroom_planks_small_bricks", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_SMALL_BRICKS_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_small_bricks_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_SMALL_TILES = BLOCKS.register("tconstruct_bloodshroom_planks_small_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_SMALL_TILES_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_small_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_SQUARES = BLOCKS.register("tconstruct_bloodshroom_planks_squares", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_SQUARES_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_squares_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_TILES = BLOCKS.register("tconstruct_bloodshroom_planks_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_TILES_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_WAVY = BLOCKS.register("tconstruct_bloodshroom_planks_wavy", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_WAVY_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_wavy_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_WOVEN = BLOCKS.register("tconstruct_bloodshroom_planks_woven", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_BLOODSHROOM_PLANKS_WOVEN_CONNECTING = BLOCKS.register("tconstruct_bloodshroom_planks_woven_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_BEAMS = BLOCKS.register("tconstruct_nahuatl_beams", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_BEAMS_CONNECTING = BLOCKS.register("tconstruct_nahuatl_beams_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_BRICKS = BLOCKS.register("tconstruct_nahuatl_bricks", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_BRICKS_CONNECTING = BLOCKS.register("tconstruct_nahuatl_bricks_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_CRATE = BLOCKS.register("tconstruct_nahuatl_crate", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_CRATE_CONNECTING = BLOCKS.register("tconstruct_nahuatl_crate_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_DIAGONAL_STRIPES = BLOCKS.register("tconstruct_nahuatl_diagonal_stripes", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_DIAGONAL_STRIPES_CONNECTING = BLOCKS.register("tconstruct_nahuatl_diagonal_stripes_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_DIAGONAL_TILES = BLOCKS.register("tconstruct_nahuatl_diagonal_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_DIAGONAL_TILES_CONNECTING = BLOCKS.register("tconstruct_nahuatl_diagonal_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_DOTTED = BLOCKS.register("tconstruct_nahuatl_dotted", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_DOTTED_CONNECTING = BLOCKS.register("tconstruct_nahuatl_dotted_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_FLOORING = BLOCKS.register("tconstruct_nahuatl_flooring", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_FLOORING_CONNECTING = BLOCKS.register("tconstruct_nahuatl_flooring_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_LARGE_TILES = BLOCKS.register("tconstruct_nahuatl_large_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_LARGE_TILES_CONNECTING = BLOCKS.register("tconstruct_nahuatl_large_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_PATTERN = BLOCKS.register("tconstruct_nahuatl_pattern", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_PATTERN_CONNECTING = BLOCKS.register("tconstruct_nahuatl_pattern_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_SMALL_BRICKS = BLOCKS.register("tconstruct_nahuatl_small_bricks", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_SMALL_BRICKS_CONNECTING = BLOCKS.register("tconstruct_nahuatl_small_bricks_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_SMALL_TILES = BLOCKS.register("tconstruct_nahuatl_small_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_SMALL_TILES_CONNECTING = BLOCKS.register("tconstruct_nahuatl_small_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_SQUARES = BLOCKS.register("tconstruct_nahuatl_squares", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_SQUARES_CONNECTING = BLOCKS.register("tconstruct_nahuatl_squares_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_TILES = BLOCKS.register("tconstruct_nahuatl_tiles", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_TILES_CONNECTING = BLOCKS.register("tconstruct_nahuatl_tiles_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_WAVY = BLOCKS.register("tconstruct_nahuatl_wavy", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_WAVY_CONNECTING = BLOCKS.register("tconstruct_nahuatl_wavy_connecting", ()-> new ChiseledBlock(true, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_WOVEN = BLOCKS.register("tconstruct_nahuatl_woven", ()-> new ChiseledBlock(false, getProperties()));
    public static RegistryObject<Block>  TCONSTRUCT_NAHUATL_WOVEN_CONNECTING = BLOCKS.register("tconstruct_nahuatl_woven_connecting", ()-> new ChiseledBlock(true, getProperties()));

    public static AbstractBlock.Properties getProperties() {
        return AbstractBlock.Properties.of(Material.WOOD, MaterialColor.WOOD).strength(2.0F, 3.0F).sound(SoundType.WOOD);    }
}