modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/Mrthomas20121/rechiseled_compat/issues"

[[mods]]
modId="rechiseled_compat"
version="1.0.4"
displayName="Rechiseled Compat"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rechiseled_compat"
#logoFile="tinkers_reforged_logo.png"
authors="Mrthomas20121"
description='''
Add other mods support to Rechiseled
'''

[[dependencies.rechiseled_compat]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rechiseled_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"