modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/FlynnLies/rechiseled_compat/issues"

[[mods]]
modId="rechiseled_compat"
version="1.1.2"
displayName="Rechiseled Compat"
displayURL="https://github.com/FlynnLies/rechiseled_compat/releases"
authors="FlynnLies, Mrthomas20121"
description='''
Adds support for other mods to Rechiseled.
'''

[[dependencies.rechiseled_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rechiseled_compat]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rechiseled_compat]]
    modId="rechiseled"
    mandatory=true
    versionRange="[1.0.12a,)"
    ordering="NONE"
    side="BOTH"