modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/Mrthomas20121/rechiseled_compat/issues"

[[mods]]
modId="rechiseled_compat"
version="1.1.2"
displayName="Rechiseled Compat"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rechiseled_compat"
#logoFile="tinkers_reforged_logo.png"
authors="FlynnLies, Mrthomas20121"
description='''
Adds support for other mods to Rechiseled.
'''

[[dependencies.rechiseled_compat]]
    modId="forge"
    mandatory=true
    versionRange="[44.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rechiseled_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rechiseled_compat]]
    modId="rechiseled"
    mandatory=true
    versionRange="[1.0.12a,)"
    ordering="NONE"
    side="BOTH"